name: ProView Installer Tests

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install runner deps
        working-directory: tools/proview-installer-test-runner
        run: |
          npm ci

      - name: Run suites
        working-directory: tools/proview-installer-test-runner
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: gpt-4o-mini
          TEMP: '0.2'
          INSTALLER_PATH: ../../installers/ProViewInstallerChatGPTFormat.yaml
        run: |
          node runner.js
